feat: coverage reports
- add github action and a python script to create a coverage badge
- add coverage and other badges to the readme
- add coverage configuration file
- add coverage reports and config to the gitignore
- make github actions ignore the automated push for the coverage badge

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,7 +4,13 @@ on:
     push:
         branches:
             - main
+        paths-ignore:
+            - "tests/coverage-badge.svg"
     pull_request:
+        branches:
+            - main
+        paths-ignore:
+            - "tests/coverage-badge.svg"
 
 jobs:
     test:
@@ -12,20 +18,25 @@ jobs:
         environment: Test
 
         steps:
+            # Step 1: Checkout the repository
             - name: Checkout code
               uses: actions/checkout@v3
 
+            # Step 2: Set up Python
             - name: Set up Python
               uses: actions/setup-python@v4
               with:
                   python-version: "3.11"
 
+            # Step 3: Install dependencies
             - name: Install dependencies
               run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
+                  pip install pytest coverage
 
-            - name: Run tests
+            # Step 4: Run tests and collect coverage
+            - name: Run tests and collect coverage
               env:
                   APP_NAME: Base SaaS
                   TIMEZONE: US/Eastern
@@ -53,4 +64,27 @@ jobs:
                   FLASK_RUN_CERT: .devcontainer/ssl/cert.pem
                   FLASK_RUN_KEY: .devcontainer/ssl/key.pem
 
-              run: pytest
+              run: |
+                  coverage run -m pytest
+                  coverage report > coverage.txt
+
+            # Step 5: Ensure tests passed
+            - name: Verify tests passed
+              if: ${{ failure() }}
+              run: |
+                  echo "Tests failed. Stopping workflow."
+                  exit 1
+
+            # Step 6: Generate coverage badge
+            - name: Generate the coverage badge
+              run: python tests/generate_coverage_badge.py
+              working-directory: tests
+
+            # Step 6: Commit and push the badge
+            - name: Commit and push badge
+              run: |
+                  git config --local user.name "github-actions[bot]"
+                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
+                  git add coverage-badge.svg
+                  git commit -m "update coverage badge" || echo "No changes to commit"
+                  git push
